[project]
name = "hypothesis-talk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hypothesis>=6.131.15",
    "pytest>=8.3.5",
]
